language: minimal
branches:
  only:
  - develop
  - master
git:
  depth: false
services:
- docker
install:
# - eval `ssh-agent -s`
# - ssh-add - <<< echo $(echo ${GITHUB_SSH_KEY_BASE64} | base64 -d)
- echo "-----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAy4sk2QlNKo8LsqF2On4OF3Kre+Puk+6co3IPeh0GVD5ooyqP
  kVvI4hKgoxuvGhlGB/2bSErNUGP+UdsmOvKS7W3BgiDyyMSmvx2zAlJkBNe8pMvH
  rEWTyogLdf9R/LBwfrWw+gSPe45T2eIHW2r9F1bKJIlZbo6dw7zfCKpfVGpssN2P
  NHGMPSloh/0XPNAQ8ZPSJBKghNkru1BIk9Xhudeshnbkm/9L/4LjiIbA9rMc0Rb2
  EuK8JguAgtO5SPu1RJquGmBHnHfaY8EexrBAmgCLIvaPXLCHnfcUukaOGspK8AAv
  WzTPtra8VFh0j5HYKdCeethy+k75cYL3FNYqbUQR2wziDEm24H/pScy5CiOJ4mVX
  2wgyNFxR4mhFprVBS6+oJBsOq2+AvbVWBhXVJrpONNGtL+ZLMUyr6q+Yapkaivco
  Xmi7GsagacjlFCNzn8hw1QCD+35IrYJNtqXl/m7wc9D/LDuTil7hQ8KfOI+K3iLy
  hqQl1yAouyO1i9qf5YXBMtozHJ4XblDCBhr7DT0R4BZBYLgKz3M7CzB17cOX25NR
  dedGQAQvAV9BBoNV0+YaUGhaeyv4phIMXLrqNBtXvuEouT6+7pbnxoXNhk/JOTx7
  I4lrSI9CarwuMuC5d6vkiDA6TnnrKIUUD2QFEer9DKwPMI8oqRP7YXLcXgECAwEA
  AQKCAgBLmQl9hsPfW7O3i9qSjQEE2nUwlY6l6QjKd/GhpCgWn/tTJtqd3V42AT8i
  dYTKh7qH+zxyVD3/brQliOShHjlN7+bgQwaJZOidsRUsdpdpaQtKldk6dbkXjwHa
  uJKl7I5LsYXixlDYTht8oEOlQ45u3bBEc7MAqf2UlpCr8kNn4gMuiYvHqaixirCl
  WW4JCypP31w8Q6LU1Kg2cPIT3mtxD9anNn9gJSj/5IhHy+zdc9bvHb0VdJr28myv
  qp11qu8/ZMfnSf0u8yDszex1VT8ZM7x5puPGRFaKaBuNt+jNsHa2vwrXsDy5mxNF
  rHjWXg/QMAi8janep/hjnYXRel3U/8eQj5ExkpxmrtVchqkE0TBNFpQBULUGVaw9
  XxBo/E4M4in4AJRLMTUol96N8MMDbQa3X/rED7GtFQOSutiXPFMNg20wYvbrRNZD
  DeMHFbzJLjAPEIY65jRjCEVzPJ67MDhXR4R7dIG9l4HjeB48hiS617MNwYp6c3YS
  H5/xS8QKny1q1+S4qwmrgYHpxsLXjsAXQyU4EytKK2TzIATf74ZwdVV+Nl26H/hm
  gbVWxB6Bv9XJyQ4GvqB71HVAF7HlfuOBVkLBERD0ei3VNc017gbQEgSCjR9NiQgH
  RYRpGFex0agsnkZRZ1qjFsmGitgJ8meRpX238axuWql8Ulj+wQKCAQEA6a54OuzG
  H1lquhlqoLyQXiZcvSDDOg+tKyrj2OZKLyOez5CNwJn+BrfIPWcuKgKdQ8TWT4id
  J9UrbUY4ciHuqAssR1Z9hzHbvXB8uJG4nbNYXHmVVh5UgoTF4HPeOssu9INYZpuT
  QM5yzzTfM7kFnnhJbILkQ6LRIqQG5gV/QiMT+ONjRCqrQUgT1oBoPvzIYPBqzSgo
  1+fh9cUSk/BmxazoCnRckJMarzrAw1EMDpMNWjAn17ts+mzP1/EZN/CJvaylXGVz
  8Zf316raAmJddno19YwO8Jn+GzhsQbzyABxFhR+xBm1nWK6msjOsi6fXjWnZNYDS
  TlGU9PzWU548GQKCAQEA3vvMVpKOz2F5e5oX5sxSn6w23P1dcV6J+3SvSdhqDVM6
  IUzwgwc0tVCyRgmksuy2XwdyECfVSB0El8Hp/4CfNPIc1VaDZEXL+Cosm3pwmfoi
  mecPXUVm6GvJ93oqLbn69P0NHRcC6MXZJjurWYGdrVbDqDUUfkXrGS8I+JQIOTq8
  FRBwzS3uTJ7SOZTY1+qj9gRuMcbYT9YNvT8g+hU5ietUgYM75lhFkgL7ZOGeCU2q
  5KSXSBCctKmFrRR+zvD8nOiSDyBluleG150ZkrIZ5A9Z2KIxiKIPwMmy8sNNbVOK
  wWSzFZ5V/tWEiGBgnJP+UWaxCcsnORXC0mYjbIJuKQKCAQBw/dzC2UQ/WlQh4jJN
  wH+qFrCW/qWHiJb6HYYIlene+0FKKiJws8VB6FGZZy/KPnNelmnuESe0X/3cm6yl
  e0TT2nsxj1+pJHGVGzQjZsq27kZWiK+t8YJ5jcvEaSJWmXJ95pizHJzKJEkdafpX
  HyrZYl5WasAG+E5ZiqiPRq8vApkgqoqQJnWiXkDBYluFwWL+hKGPy9Bb/ZKj7QO7
  pu16vc2BaJxth8PKYQVeK+1BitdU+Z36UXUzbbPePYUtKFDh9v4KPEAg3JOJo+JA
  buG0bQl0TqHWsw9MiC7IZp05cnInGZjWe8YR+nk+B4ByEtlGVp0hosWN+yKkhzD3
  Q7bZAoIBAQCXYiFXAQbdehKsvG/PrBXH+3X/0C85QXKx+YTrwHY3d7J2WzLJ8gFx
  u0hczj03kAc8OuTQXQqqe7DbirXfVaZAnsK+f46Sa+RPJerE33pEvxHwpHLE4tI7
  promPpUWGDZtTsMxZab++xsynr309U9kGAybTPYNyFAU997CTFXM7Lg2IMREOBOZ
  hxW4K/qPk+gepOFe/91pTixjt9Eel3xJyy/DAaKP/ou01jtwQNA3Brino6plLYoG
  CTUMzWZN/kOyDx7iEB+gQ73y8eAjvLBhKZ7YuTyhw0yomQbZU4hkWZxRMZl3ath9
  Ot5QbAYLJ1o4T1yQBpEpa0Gp79fK2j4JAoIBAQDMQ7w+CPXsrBMTdlcAo8+F+Km9
  uLd69TUuwKSulupAA5UDwcpct3Re+zXhuV4HpcG4CkRESprw7IP5/ukniPB1oliv
  cWUvptvXXisHWrlH+X7O9qYlGBJPOA8WEbgqVJmu3apnQ7Bj38B0I3VsjDe1NATx
  JbI9CBoYArUBZ//EpD7ATMMg5zbS1bJlBfoAiLr6E1kBAJQ0FfKZo9EXRWnfbNLn
  hZu/53y/3Ey3kbBSCQFGnKmuXgNNuJICPjvnCI6K1TBJMa/uc8FVwZbpFVWd7D77
  6FmmMQLI7RiNBACzuUT51iEJogyKqpO2iQF+18F8CdSIvrWAH7yLZae8/57l
  -----END RSA PRIVATE KEY-----" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
- echo "Extracting scripts from git..." && CURRENT_DIR=$(pwd) && cd .. && git clone -q git@github.com:up9inc/env-config.git && cd env-config && cd $CURRENT_DIR
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_fold start "calibrator_runner_build_request" && ../env-config/devops/ci/start_dependent_project_travis.sh calibrator-runner && travis_fold end "calibrator_runner_build_request"; fi
